"""Typed surface of the teptris._native C extension."""
from typing import Any, Union

class DecodeError(Exception):
    line: int
    column: int

class LazyNode:
    def kind(self) -> str: ...
    def value(self) -> Any: ...
    def to_dict(self) -> Any: ...
    def to_list(self) -> Any: ...

def loads(data: bytes) -> dict[str, Any]: ...
def loads_batch(docs: list[bytes]) -> list[dict[str, Any]]: ...
def loads_lazy(data: bytes) -> LazyNode: ...
def dumps(obj: Any) -> str: ...
def engine_version() -> str: ...
def plan_build(rows: list[list[Any]],
               first_row: list[int]) -> object: ...
def plan_emit(plan: object,
              toml: Union[str, bytes]) -> dict[str, Any]: ...
