"""Typed surface of the teptris._native C extension."""
from typing import Any, Iterator, Optional, Union, overload

class DecodeError(Exception):
    line: int
    column: int

class LazyNode:
    def kind(self) -> str: ...
    def value(self) -> Any: ...
    def to_dict(self) -> Any: ...
    def to_list(self) -> Any: ...
    # [] : table key (str) or array index (int). Absent table keys
    # read as None; out-of-range array indices raise IndexError.
    @overload
    def __getitem__(self, key: str) -> Optional[LazyNode]: ...
    @overload
    def __getitem__(self, index: int) -> LazyNode: ...
    # iteration: tables yield (key, LazyNode) pairs, arrays yield
    # LazyNodes, scalars raise TypeError
    def __iter__(self) -> Iterator[object]: ...
    def __len__(self) -> int: ...

def loads(data: bytes) -> dict[str, Any]: ...
def loads_batch(docs: list[bytes]) -> list[dict[str, Any]]: ...
def loads_lazy(data: bytes) -> LazyNode: ...
def dumps(obj: Any) -> str: ...
def engine_version() -> str: ...
def plan_build(rows: list[list[Any]],
               first_row: list[int]) -> object: ...
def plan_emit(plan: object,
              toml: Union[str, bytes]) -> dict[str, Any]: ...
